import {StyleSheet} from 'react-native';

const genericStyle = StyleSheet.create({
  loginBtn: {
    alignItems: 'center',
    borderWidth: 1,
    flexDirection: 'row',
    height: 48,
    marginTop: 0,
    backgroundColor: '#e8f1ff',
    borderRadius: 30,
    borderColor: '#e8f1ff',
  },

  loginBtnText: {
    textAlign: 'center',
    textTransform: 'uppercase',
    color: '#3878ee',
    width: '100%',
    fontSize: 24,
  },
  loginButton: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    justifyContent: 'center',
  },
  underline: {
    height: 1.5,
    marginTop: 2,
    width: 'auto',
    backgroundColor: '#ffbb74',
  },
  textBox: {
    height: '100%',
    width: '100%',
    backgroundColor: '#ffffff',
    borderBottomColor: '#3878ee',
    borderTopColor: '#ffffff',
    borderRightColor: '#ffffff',
    borderLeftColor: '#ffffff',
    color: '#3878ee',
    borderWidth: 1.5,
    paddingLeft: 15,
    borderRadius: 1,
    fontFamily: 'System',
  },
  searchBar: {
    height: 44,
    width: '100%',
    borderColor: '#ffffff',
    backgroundColor: '#ffffff',
    color: '#3878ee',
    borderWidth: 1,
    borderRadius: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 14,
    paddingRight: 14,
    marginTop: 0,
    fontSize: 15,
    fontFamily: 'System',
  },
  searchIcon: {
    width: 25,
    height: 25,
    alignSelf: 'center',
    right: 20,
    // tintColor: "#4b5f79",
  },
  noResultView: {
    justifyContent: 'center',
    flex: 1,
    marginBottom: 80,
    paddingHorizontal: 40,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  noResultText: {
    textAlign: 'center',
    fontSize: 18,
    fontFamily: 'System',
    color: '#3878ee',
  },
  addRemoveBox: {
    color: '#3878ee',
    fontFamily: 'System',
    textAlign: 'center',
    fontSize: 16,
  },
  addRemoveBoxText: {paddingLeft: 15, color: '#3878ee'},
  locationAddRemove: {
    paddingHorizontal: 10,
    borderColor: '#C1CAE1',
    backgroundColor: '#C1CAE1',
    borderRadius: 25,
    borderWidth: 1,
    height: 36,
    width: 'auto',
    marginRight: '3%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: 10,
  },
  removeIconlocation: {
    width: 26,
    height: 26,
    marginLeft: 5,
    // top: -12,
    right: -5,
  },
  locationEditBox: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
    marginBottom: 0,
  },
  subHeading: {
    fontSize: 20,
    textTransform: 'capitalize',
    fontFamily: 'System',
    color: '#3878ee',
    marginHorizontal: 15,
  },
  heading: {
    textTransform: 'uppercase',
    fontSize: 24,
    color: '#3878ee',
    fontWeight: '500',
  },
});

export default genericStyle;
