import { StyleSheet } from 'react-native';
import { app, grey } from '../../constants/themeColors';

const genericStyle = StyleSheet.create({
  loginBtn: {
    alignItems: 'center',
    borderWidth: 1,
    flexDirection: 'row',
    height: 48,
    marginTop: 0,
    backgroundColor: app.lightBlue,
    borderRadius: 30,
    borderColor: app.lightBlue,
  },

  loginBtnText: {
    textAlign: 'center',
    textTransform: 'uppercase',
    color: '#ffffff',
    width: '100%',
    fontSize: 18,
  },
  loginButton: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    marginBottom: 10
  },
  underline: {
    height: 1.5,
    marginTop: 2,
    width: 'auto',
    backgroundColor: grey[600],
  },
  textArea: {
    height: '100%',
    width: '100%',
    backgroundColor: '#ffffff',
    borderBottomColor: '#adb5bd',
    borderTopColor: '#adb5bd',
    borderRightColor: '#adb5bd',
    borderLeftColor: '#adb5bd',
    // color: app.lightBlue,
    borderWidth: 1.5,
    paddingLeft: 15,
    borderRadius: 10,
    fontFamily: 'System',
    textAlignVertical: 'top'
  },
  textAreaFocused: {
    height: '100%',
    width: '100%',
    backgroundColor: '#ffffff',
    borderBottomColor: app.lightBlue,
    borderTopColor: app.lightBlue,
    borderRightColor: app.lightBlue,
    borderLeftColor: app.lightBlue,
    color: app.lightBlue,
    borderWidth: 1.5,
    paddingLeft: 15,
    borderRadius: 25,
    fontFamily: 'System',
  },
  textBox: {
    height: '100%',
    width: '100%',
    backgroundColor: '#ffffff',
    borderBottomColor: '#adb5bd',
    borderTopColor: '#adb5bd',
    borderRightColor: '#adb5bd',
    borderLeftColor: '#adb5bd',
    // color: app.lightBlue,
    borderWidth: 1.5,
    paddingLeft: 15,
    borderRadius: 25,
    fontFamily: 'System',
  },
  textBoxFocused: {
    height: '100%',
    width: '100%',
    backgroundColor: '#ffffff',
    borderBottomColor: app.lightBlue,
    borderTopColor: app.lightBlue,
    borderRightColor: app.lightBlue,
    borderLeftColor: app.lightBlue,
    color: app.lightBlue,
    borderWidth: 1.5,
    paddingLeft: 15,
    borderRadius: 25,
    fontFamily: 'System',
  },
  searchBar: {
    height: 44,
    width: '100%',
    borderColor: '#ffffff',
    backgroundColor: '#ffffff',
    color: '#3878ee',
    borderWidth: 1,
    borderRadius: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 14,
    paddingRight: 14,
    marginTop: 0,
    fontSize: 15,
    fontFamily: 'System',
  },
  searchIcon: {
    width: 25,
    height: 25,
    alignSelf: 'center',
    right: 20,
    // tintColor: "#4b5f79",
  },
  noResultView: {
    justifyContent: 'center',
    flex: 1,
    marginBottom: 80,
    paddingHorizontal: 40,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  noResultText: {
    textAlign: 'center',
    fontSize: 18,
    fontFamily: 'System',
    color: '#3878ee',
  },
  addRemoveBox: {
    color: '#fff',
    fontFamily: 'System',
    textAlign: 'center',
    fontSize: 16,
  },
  addRemoveBoxText: { paddingLeft: 15, color: '#ffffff' },
  locationAddRemove: {
    paddingHorizontal: 10,
    borderColor: app.lightBlue,
    backgroundColor: app.lightBlue,
    borderRadius: 25,
    borderWidth: 1,
    height: 36,
    width: 'auto',
    marginRight: '3%',
    flexDirection: 'row',
    // justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: 10,
    color: "#fff",
    tintColor: "#fff"
  },
  removeIconlocation: {
    width: 20,
    height: 20,
    marginLeft: 5,
    // top: -12,
    right: -5,
    tintColor: "#fff"
  },
  locationEditBox: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
    marginBottom: 0,
  },
  subHeading: {
    fontSize: 20,
    textTransform: 'capitalize',
    fontFamily: 'System',
    color: app.lightBlue,
    marginHorizontal: 15,
  },
  heading: {
    textTransform: 'uppercase',
    fontSize: 24,
    color: app.lightBlue,
    fontWeight: '500',
  },
});

export default genericStyle;
